spring.datasource.url=jdbc:postgresql://dpg-abc123:5432/complaintdb_kwg1
spring.datasource.username=complaintdb_kwgl_user
spring.datasource.password=xHA8iDChDkUddUdkGfvxmXluIoszyG47
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true